### ISSUE TITLE
Talks by měl být stejný objekt jako workshops

### ISSUE THREAD

**Issue by benabraham** [pyvec/cz.pycon.org-2019#1]
Nedává smysl to oddělovat, protože je skoro vše stejné a pak to jen komplikuje šablony.

**Comment by encukou** [comment]
Mělo by se to spojit do `Session`. Ideálně před CfP 2020.

**Comment by benabraham** [comment]
Ono to vlastně není špatně. Něco mají společné, nějaké vlastnosti jsou specifické pro přednášky a některé pro workshopy, mě vlastně vadí to, jak s tím zatím musím pracovat v šablonách.

**Comment by benabraham** [comment]
šablony jsou teď v pohodě, takže zbývá jen otázka, co je lepší mít v Pythonu
