### ISSUE TITLE
Change order of sessions

### ISSUE THREAD

**Issue by benabraham** [pyvec/cz.pycon.org-2019#126]
Allow to set a number which will override default order for sessions

**Comment by encukou** [comment]
How will numbered sessions be ordered relative to unnumbered sessions?
What's the use case here?

**Comment by benabraham** [comment]
Number will be required with default 100, so it would be easily possible to move any of 30+ sessions before their default position.

Use case is we want to direct the order of sessions. 
For example this year if we will publish part of sessions later we might want them to stick together at the top (or bottom) so it's easier for attendees to check what is new. 

Or those two-speaker sessions in some combinations create weird layouts, so we would need to change their position in HTML.

Or if somebody has more than one session of the same type we would like to have them together.

Or PyData track sessions.

I know some of these can be solved by grouping by those properties but not all and order is a generally working solution.
