### ISSUE TITLE
Session detail: Next and previous session

### ISSUE THREAD

**Issue by benabraham** [pyvec/cz.pycon.org-2019#127]
Two links to the next and the previous session (order as they are sorted on listing).

Nice to have: on the last item get a link to the first and on the first item, get a link to the last one.

**Comment by encukou** [comment]
Shouldn't this be based on the slots (times/rooms) instead?

**Comment by encukou** [comment]
Ah, sorry, that's #128.
I don't see this as necessary – it seems the schedule will be done very soon after talks are finalized.

**Comment by benabraham** [comment]
But won't be published (according to current plan), because of expected changes.
So there's about a 2-month period when this is usable.

Also we would probably switch back to this version after the conference. 🤔
