### ISSUE TITLE
Menu snadněji

### ISSUE THREAD

**Issue by benabraham** [pyvec/cz.pycon.org-2019#17]
Menu by se měla definovat snadněji. 

Nevím jestli přes admin, ale chtělo by to nějak.

**Comment by encukou** [comment]
@starenka Šlo by věci kolem `PHASE_CURRENT` prostrkat do šablon, abych mohl v šabloně říct něco jako `if PHASE > PHASES['10-date-place']`? Já se v těch fázích moc nevyznám, ale předpokládám že se je to teď založené hlavně na copy&paste a dalo by se to takhle zjednodušit. Včetně menu.

**Comment by benabraham** [comment]
@encukou ty PHASE… byl takovej můj zoufalej pokus to letos vyřešit aspoň nějak. Takže bych radši neoptimalizoval nic moc řešení a vyřešil to pořádně.

**Comment by benabraham** [comment]
a možná není nutno, pokud se dobře vyřeší #5 (v podstatě lepší náhrada fází)

**Comment by starenka** [comment]
Ja vo fazich radsi nic nevim, jejich predchudce sem taky neschvaloval, to
je danova pandorina skrinka :p

---
aknerats[::-1]
