### ISSUE TITLE
Program by měl umět speciální položky

### ISSUE THREAD

**Issue by benabraham** [pyvec/cz.pycon.org-2019#20]
Položky jako Snídaně apod. by měly být snadno přidatelné do programu.

**Comment by frenzymadness** [comment]
Nový model pro speciální položky s:

- Název **(required)**
- Popis
- URL na samostatnou stránku

**Comment by benabraham** [comment]
K URL dodám, že by mělo být možné i relativní (k rootu), tedy třeba `/2019/coc/`, aby pohodlně fungovala beta i lokální vývoj.
