### ISSUE TITLE
Inform speakers about accessibility considerations

### ISSUE THREAD

**Issue by encukou** [pyvec/cz.pycon.org-2019#206]
Vojta, a blind Pythonista that attended last year's PyCon, shared a few notes on how to make the talks more accessible. They should be made available to speakers (maybe as part CfP, perhaps as part of some instructions on how to do a talk).

The text went to info@pyvec via @kejbaly2, don't know yet if I can share it here.

**Comment by benabraham** [comment]
https://blog.python.cz/blind-attendee-about-pycon-cz-2016

**Comment by benabraham** [comment]
included in #223
