### ISSUE TITLE
Annotate times on youtube conference videos.

### ISSUE THREAD

**Issue by Magwit** [pyvec/cz.pycon.org-2019#209]

**Comment by Magwit** [comment]
Starting with ballroom day 1.

**Comment by Magwit** [comment]
# Balllroom day one

## welcome presentation 


https://youtu.be/5JDtLnUbF6Q?t=719

## Josef Svoboda: Leveraging Technology and Laziness

https://youtu.be/5JDtLnUbF6Q?t=1208

## Svitoslav Sydorenko: GitHub Bots: Rise of the Machines

https://youtu.be/5JDtLnUbF6Q?t=4415

## Anastázie Sedláková: Mindful Learning

https://youtu.be/5JDtLnUbF6Q?t=6923

## Juha-Matti Sankala: I Teach, Therefore I Learn

https://youtu.be/5JDtLnUbF6Q?t=8803

## Karla Fejfarová: Of Mice and Men and Python

https://youtu.be/5JDtLnUbF6Q?t=14384

## Flavio Percoco:  Inheriting Code, and I Don't Mean Classes

https://youtu.be/5JDtLnUbF6Q?t=17863

## Miroslav Pojman: Iterators for Curious Minds

https://youtu.be/5JDtLnUbF6Q?t=20214

## Pavel Šmerda: Debugging Binaries with Python

https://youtu.be/5JDtLnUbF6Q?t=23815

## Miro Hrončok: #! Bang, bang! 

https://youtu.be/5JDtLnUbF6Q?t=26227

## Lightning Talks Day One

https://youtu.be/5JDtLnUbF6Q?t=28576

**Comment by Magwit** [comment]
# Club Day One

## Tania Allard: Jupyter Notebooks: Friend or Foe

https://youtu.be/mniWotxI4C8

## Petr Šimeček: Time Series Forecasting in Python

https://youtu.be/mniWotxI4C8?t=2125

## Jakub Langr: The Theory and Practice of Generative Adversarial Networks (GANS)

https://youtu.be/mniWotxI4C8?t=4439

## Galuh Sahid: An Introduction to Word Embeddings

https://youtu.be/mniWotxI4C8?t=9291

## Jan Pipek: Practical Guide to Designing Implants for Pandas

https://youtu.be/mniWotxI4C8?t=11656

## Juantomás García: AbadIA Using Reinforcement Learning to Play and Solve The Abbey of Crime

https://youtu.be/mniWotxI4C8?t=15120


## Piotr Grzesik: AWS Machine Learning Application Services for Pythonistas

https://youtu.be/mniWotxI4C8?t=17533

**Comment by Magwit** [comment]
# Ballroom Day Two

## Jackie Kazil: Parallels Between Career Building and Home Remodeling

https://youtu.be/3ci5jFykVxo?t=1086

## Gabriel Bianconi: Face processing with Computer Vision

https://youtu.be/3ci5jFykVxo?t=3961

## Veronika Hanus: To Comment or Not? A Data-Driven Look at Attitudes Towards Code Comments

https://youtu.be/3ci5jFykVxo?t=6182

## Miroslav Šedivý: A Day Has Only 24±1 Hours

https://youtu.be/3ci5jFykVxo?t=8464

## Mislav Cimperšak: On the Edge of Leadership

https://youtu.be/3ci5jFykVxo?t=13688

## Petr Viktorin: Building and Async Event Loop

https://youtu.be/3ci5jFykVxo?t=17355

## Luka Raljević: Maintaining Peace by Preparing for War

https://youtu.be/3ci5jFykVxo?t=19648

## Nick Lang: Intro to Search Using Python

https://youtu.be/3ci5jFykVxo?t=23231

## Jan Škoda: Performance Tuning in Python

https://youtu.be/3ci5jFykVxo?t=25606

## Lightning Talks Day Two

https://youtu.be/3ci5jFykVxo?t=28074

**Comment by Magwit** [comment]
# Club Day Two


## Jan Bednařík: Electronics with Python for Beginners

https://youtu.be/P3X0n-a0_hI?t=721

## Tomáš Vondra: PostgreSQL vs. Data Corruption

https://youtu.be/P3X0n-a0_hI?t=2737

## Marcel Plch: What are CPython's Subinterpreters?

https://youtu.be/P3X0n-a0_hI?t=5680

## Angelina Nikiforova: Keep Formatting Consistent with Black

https://youtu.be/P3X0n-a0_hI?t=14122

## Vojta Filipec: Curious About a New Place? Get There via Openstreetmap API

https://youtu.be/P3X0n-a0_hI?t=16527


## Glutexo: Unicodem k Bezpečnosti

https://youtu.be/P3X0n-a0_hI?t=20115


## Dariusz Aniszewski: Git Under the Hood

https://youtu.be/P3X0n-a0_hI?t=22514

**Comment by encukou** [comment]
Thank you very much!

**Comment by hroncok** [comment]
I have a sad information. When clicking the links from the youtube vide description, the ?t=xyz part gets eaten and it doesn't work. I think it si not worth replacing with timestamps, baring the fact that this is all just temporary, but maybe we can add a note that the links need to be copied and pasted?

**Comment by messa** [comment]
why not worth it replacing with timestamps?

**Comment by hroncok** [comment]
I hope we get separate videos soon.

**Comment by benabraham** [comment]
@hroncok not soon enough, if somebody can do the work, please do

**Comment by encukou** [comment]
Also, some of the videos are unavailable. Apparently, some of the background music was copyrighted.

**Comment by encukou** [comment]
Updated comments with H:MM:SS timestamps.

**Comment by frenzymadness** [comment]
> Also, some of the videos are unavailable. Apparently, some of the background music was copyrighted.

:man_facepalming:
