### ISSUE TITLE
Udělat fixture s dummy datama

### ISSUE THREAD

**Issue by benabraham** [pyvec/cz.pycon.org-2019#23]
Talky, workshopy atd.

**Comment by frenzymadness** [comment]
Pracuji na skriptu, který naplní databázi náhodně generovanými (ale smysluplnými) daty pomocí knihovny [Faker](https://faker.readthedocs.io/en/master/index.html).

**Comment by benabraham** [comment]
Myslím, že bohatě stačí vzít vhodná data z minulých let.

**Comment by benabraham** [comment]
Dokonce je lepší mít tam skutečné texty než Lorem ipsum libovolného druhu.

**Comment by frenzymadness** [comment]
Ok, může nám @starenka udělat dump letošní DB? Nebo dát do ní přístupy?

**Comment by frenzymadness** [comment]
Jaká data z toho ale vlastně můžeme použít? Jména, emaily, odkazy na socky, bia atp. bych asi dal pryč, takže nám zůstávají popisy jednotlivých talků/workshopů.

Vážně by nedávalo smysl je všechny nafejkovat? Navíc, když se napíše skript, který tu databázi naplní, bude se to daleko snáze udržovat než dump databáze v SQL souboru.

Chtěl bych to mít veřejně v repu, aby si kadý místo klikání v adminu jen spustil skript a měl nějaká data v db, ale to se celkem vylučuje s cistlivostí reálných dat z loňských let.

**Comment by frenzymadness** [comment]
Fixed in https://github.com/pyvec/cz.pycon.org-2019/pull/31
