### ISSUE TITLE
Lístky na workshopy: párování s účastníky

### ISSUE THREAD

**Issue by benabraham** [pyvec/cz.pycon.org-2019#24]
Je potřeba zajistit aby 
1) lístky na workshopy mohli registrovat pouze účastníci
2) nešlo registrovat více workshopů pro jednoho účastníka na stejnou dobu

Ti.to to přímo nezvládá. 

Máme řešení bez API založené na slevových kupónech.

- [x] (nutno přidat ID workshopu z Ti.to ke každému workshopu v naší db) (@benabraham)
- [x] Budeme chtít mít na detailu workshopu input pro kód lístku + tlačítko pro registraci daného workshopu (@benabraham)
- [x] Extra: Tlačítko vylepšit o to, že se místo něj zobrazí vyprodáno, pokud je vyprodáno (@mcurlej)
- [x] Extra extra: v přehledu workshopů zobrazit vyprodáno

**Comment by benabraham** [comment]
Máme řešení bez API založené na slevových kupónech.

**Comment by frenzymadness** [comment]
Poslední bod pro @mcurlej - získat pomocí JS z tita informaci, zda je lístek pro konkrétní WS vyprodán a pokud ano, promítnout tuhle informaci do stránky detailu WS.

**Comment by benabraham** [comment]
V přehledu workshopů lze zobrazit vyprodáno přes phase.
