### ISSUE TITLE
proposals/emails/*.tpl

### ISSUE THREAD

**Issue by benabraham** [pyvec/cz.pycon.org-2019#26]
Not sure what to do with them: https://github.com/pyvec/cz.pycon.org-2018/issues/31

**Comment by frenzymadness** [comment]
I think that we can remove files which won't be used after issue https://github.com/pyvec/cz.pycon.org-2019/issues/27 solution.

**Comment by benabraham** [comment]
Depends if we want to send results automatically (using this system) or not.
Anyway, will make a new issue.
