### ISSUE TITLE
Front End Stack should be more secure: it shouldn't require global installation and NPM packages should be updated

### ISSUE THREAD

**Issue by frenzymadness** [pyvec/cz.pycon.org-2019#28]
Je potřeba udělat update závislostí, protože řada z nich obsahuje bezpečnostní zranitelnosti

https://github.com/pyvec/cz.pycon.org-2019/network/alerts

**Comment by benabraham** [comment]
Přesně tak. Je to jen lokální build (krom toho scrollspy z Bootstrapu, kterej stejně nepoužíváme), čímž neříkám, že to nebumpnem, ale ony tam zas budou jiný…

**Comment by benabraham** [comment]
Global installation was not needed anyway, it was just an error in documentation (is fixed now).

Packages are bumped.
