### ISSUE TITLE
Team photos too large in second row

### ISSUE THREAD

**Issue by hroncok** [pyvec/cz.pycon.org-2019#35]
https://cz.pycon.org/2019/about/team/

![_](https://user-images.githubusercontent.com/2401856/50005200-d1d8c380-ffa9-11e8-973a-1380ee90824e.png)

The second row is always bigger. If you refresh, you get different people, but still bigger.

**Comment by hroncok** [comment]
Actually:

![_](https://user-images.githubusercontent.com/2401856/50006156-19148380-ffad-11e8-98db-db9fd934b90f.png)

**Comment by hroncok** [comment]
Adding more less/people won't help, because it changes as I resize the window:

![_](https://user-images.githubusercontent.com/2401856/50006215-43664100-ffad-11e8-925e-2a35e01b522c.png)

**Comment by frenzymadness** [comment]
Yes, but the highest count of photos in one line is six so the best count is 12 IMHO. Will see how it'll behave when I fill it.
