### ISSUE TITLE
Mitigate vulnerabilities

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/cz.pycon.org-2019#38]
See https://github.com/pyvec/cz.pycon.org-2019/network/alerts

--------

<img width="545" alt="screenshot 2018-12-18 at 10 15 05" src="https://user-images.githubusercontent.com/283441/50143788-d35a0280-02ad-11e9-8ade-0a30528b57f9.png">

**Comment by frenzymadness** [comment]
This issue is already here: https://github.com/pyvec/cz.pycon.org-2019/issues/28

**Comment by encukou** [comment]
> See https://github.com/pyvec/cz.pycon.org-2019/network/alerts

BTW, that page only appears to repo admins.

**Comment by honzajavorek** [comment]
I’m sorry!

**Comment by frenzymadness** [comment]
Don't be sorry. Two times is always better than never :+1:
