### ISSUE TITLE
Položka programu by měla mít začátek i konec

### ISSUE THREAD

**Issue by benabraham** [pyvec/cz.pycon.org-2019#4]
+ jako datetime
+ validovat aby se ve stejné místnosti nepřekrývaly

**Comment by frenzymadness** [comment]
Takže jako další datetime field pro každý slot?

**Comment by benabraham** [comment]
nebo délku jako duration https://docs.djangoproject.com/en/1.11/ref/models/fields/#durationfield
nemám názor na to, co je vhodnější

**Comment by frenzymadness** [comment]
Ono asi záleží na tom, jak tu informaci budeme chtít zobrazovat na frontendu. Pokud si udložíme duration a budeme chtít zobrazovat čas konce, budeme to muset počítat, stejně tak pokud si uložíme čas konce a budeme chtít zobrazovat délku. Je to sice jen jeden řádek navíc, ale i tak tam být nemusí.

Také nemám preferenci, jestli bych v programu raději viděl začátek a konec nebo začátek a dobu trvání.

**Comment by benabraham** [comment]
Ještě je tam sekundární důvod a to abychom mohli validovat, že se sloty v jedné místnosti nepřekrývají

**Comment by frenzymadness** [comment]
Vzhledem k validaci bude lepší, když bude konec jako `datetime` a duration se případně vypočítá, pokud bude potřeba do šablony.
