### ISSUE TITLE
Sync design of main headings

### ISSUE THREAD

**Issue by frenzymadness** [pyvec/cz.pycon.org-2019#48]
IMHO every page main heading should use the same design as on Code of Conduct page:

![image](https://user-images.githubusercontent.com/5688939/51494591-66a8bb00-1db9-11e9-86c0-c2d86b16cffa.png)

which is not currently true

![image](https://user-images.githubusercontent.com/5688939/51494610-7a542180-1db9-11e9-9f14-7b7e0e0296de.png)

I think that the design with the brown stripe is better so I'd apply the same to other pages. Anyone against?

**Comment by encukou** [comment]
See notes in [README](https://github.com/pyvec/cz.pycon.org-2019#html). (With CFP's small sections, you don't need to strictly alternate odd/even).

**Comment by frenzymadness** [comment]
I don't want to alternate sections, I just want to use the brown strip for every main heading. And yes, I found that it can be simply done with `span` inside `h1` before somebody implements a better solution.

I just wanted to ask for opinions before I implement it. Do you think it's a good idea?

**Comment by encukou** [comment]
Yes.

**Comment by benabraham** [comment]
You can add those spans, but I'll focus on more pressing matters…
