### ISSUE TITLE
Zobrazování informací na frontendu ovládáné z adminu

### ISSUE THREAD

**Issue by benabraham** [pyvec/cz.pycon.org-2019#5]
1) ručně: true/false/hodnota
2) automaticky: různé hodnoty dle aktuálního času (možnost override dle 1)

**Comment by benabraham** [comment]
Tady jsou konkrétní položky a jejich možné hodnoty:

# Date
- unknown
- announced

# City
- unknown
- announced

# Venue
- unknown
- announced

# Ticket Sales 
souvisí s #3 
pro každý typ lístku (early bird, standard, late bird) zvlášť
- not launched
- opened
- sold out
- timed out

# Schedule
- not public
- published

# City Info
- not public
- published

# Extra event (e.g. board game night)
- not public
- opened
- sold out
- timed out

# Streams 
(status is on pycon.cz, not YT and is for all videos together)
- not public
- live
- some past
- all past
- hidden

# Final Videos
- non existent
- not public
- public

**Comment by encukou** [comment]
OK, jdu kouknout jestli zvládnu přidat:

* model `SiteFlag` se:
   * jménem
   * hodnotou -- True, False, "turn on at", "turn off at"
   * datumočasem zapnutí/vypnutí

* helper get_site_flag(), který vrátí True/False pro dané jméno.

**Comment by encukou** [comment]
Myslím že by to šlo booleanama, viz níže.
Bylo by to IMO flexibilnější v tom, že nemusíš definovat možné hodnoty u každé položky.

### Date
- [ ] `date_announced`

### City
- [ ] `city_announced`

### Venue
- [ ] `venue_announced`

### Ticket Sales
- [ ] `tickets_launched`
- [ ] `tickets_soldout_early`
- [ ] `tickets_soldout_standard`
- [ ] `tickets_soldout_late`
- [ ] `tickets_soldout_...`
- [ ] `tickets_over`

### Schedule
- [ ] `schedule_published`

### City Info
- [ ] `city_published`

### Extra event (e.g. board game night)
- [ ] `bgn_published`
- [ ] `bgn_selling`
- [ ] `bgn_soldout`

### Streams 
(status is on pycon.cz, not YT and is for all videos together)
?

### Final Videos
- [ ] `videos_available`
- [ ] `videos_published`

**Comment by frenzymadness** [comment]
Co na to navrhovatel? @benabraham

**Comment by benabraham** [comment]
Hodím sem „do záznamu“, co jsem psal na Slacku:

> Pocit, že to bude snazší v adminu nebo v šablonách než ta mnou navržená hierarchie zatím bohužel nesdílím. :thinking_face:
> 
> Pořád si myslím, že jedna věc (třeba prodej lístků) má v daným čase právě jeden status (vyprodáno).
Proto mi pořád nehraje to, že tenhle mentální model se neodráží v tom, jak ty data jsou.  :exploding_head:
> 
> Ale zatím mě to neblokuje a můžu to zkusit použít tak jak to je a uvidíme, jestli v praxi narazím nebo ne. :man-shrugging:

**Comment by benabraham** [comment]
Tady ještě moje ideální představa :) s využitím tabularInline z contrib.admin
+ nějakej způsob jak i na betě přepnout datetime, co se pro rozhodování používá

![image](https://user-images.githubusercontent.com/334494/53700505-5261d000-3df3-11e9-8b0b-abc0363660ba.png)
