### ISSUE TITLE
Keynotes on homepage

### ISSUE THREAD

**Issue by frenzymadness** [pyvec/cz.pycon.org-2019#51]
We need to create a design we'll use for keynotes announcements as a part of main page (keynotes)
Design deadline: 2019-02-18 (end of CfP)
Implementation deadlines:
- 2019-02-25 (early birds start, keynoters going public)
- 2019-03-18 (talks going public)

Cc: @encukou

**Comment by benabraham** [comment]
These are 2 issues in one.
