### ISSUE TITLE
Proposals / Fin Aid results mass replies

### ISSUE THREAD

**Issue by benabraham** [pyvec/cz.pycon.org-2019#57]
Do we want to use this system to send e-mails with CfP and Finaid results?

These templates need to be updated (and make it work actually?)

```
accepted_aid.tpl
accepted_sprint.tpl
accepted_talk.tpl
accepted_workshop.tpl
```

Also there are no templates (and probably no functionality) for refused talks which would be a common courtesy to send.

**Comment by frenzymadness** [comment]
I think that we can prepare/update some manage command to do it. But we'll need to set up SMTP first.

Could you please prepare email templates?

**Comment by benabraham** [comment]
Mailchimp or sending from info@pycon.cz with [Thunderbird extension](https://addons.thunderbird.net/en-US/thunderbird/addon/mail-merge/) is probably simpler.

Reopen if you disagree
