### ISSUE TITLE
Consider secret early bird tickets as sold out

### ISSUE THREAD

**Issue by benabraham** [pyvec/cz.pycon.org-2019#78]
We need to have tickets available for companies paying by invoice but no more available publicly.

We can switch them to secret tickets so they should be considered the same as soldout.

**Comment by frenzymadness** [comment]
This should be closed automatically by merged PR.

**Comment by benabraham** [comment]
@frenzymadness yeah, I used one word that doesn't do that by mistake 🤦‍♂️ 

close
closes
closed
fix
fixes
fixed
resolve
resolves
resolved
