### ISSUE TITLE
Náhledová verze webu

### ISSUE THREAD

**Issue by benabraham** [pyvec/cz.pycon.org-2019#8]
Nevím jak přesně řešit, ale bylo by fajn mít web, kde jsou publikované nové věci ke schválení sponzory, speakery, ostatními orgy atd. 

Ideálně ze stejné DB, prostě jen status, který se po schválení přepne na veřejný.

**Comment by frenzymadness** [comment]
Nevím, jestli to není moc práce navíc. Nemohli bychom pro tohle použít betu? Kolik je takových speakerů/sponzorů, kteří to nutně potřebují vidět a schválit před publikací veřejně? Většinou se to nějak ukáže a pak se případně opraví chyby či doladí detaily.

**Comment by benabraham** [comment]
Hlavně to teď jde řešit přes phases případně.
