### ISSUE TITLE
Programme/workshop admin doesn't allow to save 3 hour workshop

### ISSUE THREAD

**Issue by benabraham** [pyvec/cz.pycon.org-2019#87]
Admin shows 2 hours (can't save 3 hours).
Because of this?

```
 LENGTH = (
        ('1h', '1 hour'),
        ('2h', '2 hours'),
        ('2h', '3 hours'),
        ('1d', 'Full day (most sprints go here!)'),
        ('xx', 'Something else! (Please leave a note in the abstract)')
 )
```

Everybody in accepted proposals has 3 hour workshop (except Caletka)

FYI @frenzymadness

**Comment by frenzymadness** [comment]
It's not a critical bug this year because all workshops will have 3-hour slot available no matter what they asked for.
