### ISSUE TITLE
Registrace na workshopy (stavy)

### ISSUE THREAD

**Issue by benabraham** [pyvec/cz.pycon.org-2019#9]
možné stavy

- not launched
- opened
- sold out
- waiting list
- opened for ppl on waiting list
- offered
- accepted
- timed out

**Comment by frenzymadness** [comment]
Related to: https://github.com/pyvec/cz.pycon.org-2019/issues/24

**Comment by benabraham** [comment]
Nebudeme mít waiting list, takže máme vyřešeno přes Phases globálně.

Stav jednotlivých workshopů asi přes API podobně jako lístky.
