### ISSUE TITLE
Simplify phases usage in templates {{ phases.PHASENAME.PHASEVALUE }} true or false

### ISSUE THREAD

**Issue by benabraham** [pyvec/cz.pycon.org-2019#98]
`{{ phases.PHASENAME.PHASEVALUE }}` should return True if it's current phasevalue.

In all other cases (not current, non existent, not active) False should be ok.

**Comment by encukou** [comment]
What is wrong with {{phases.PHASENAME == 'PHASEVALUE'}}?

**Comment by benabraham** [comment]
There is probably nothing that can't be done with it as it is now. I'd keep `{{ phases.PHASENAME }}` and add the simpler boolean which might make more complex comparisons in templates shorter. 

Again, just saving ideas for later. No need to worry about this now.

**Comment by encukou** [comment]
But if `{{phases.PHASENAME == 'PHASEVALUE'}}` works, that means `phases.PHASENAME` is a string – not a container of PHASEVALUEs, as `{{ phases.PHASENAME.PHASEVALUE }}` would suggest.

**Comment by benabraham** [comment]
Can't it be both? The string is a string representation of phase object and values are properties?

My PyFu is weak here though…

**Comment by starenka** [comment]
afaik you can use `{% ifnotequal obj|stringformat:"s" stringval %}` but
please DON'T
---
In Perl you shoot yourself in the foot, but nobody can understand how you
did it. Six months later, neither can you. | print 'aknerats'[::-1]

**Comment by starenka** [comment]
anyway you can still make a filter/tag for the comparsions, but why?
---
In Perl you shoot yourself in the foot, but nobody can understand how you
did it. Six months later, neither can you. | print 'aknerats'[::-1]

**Comment by benabraham** [comment]
I guess `==` works differently in django templates?

@starenka I'm not even sure you're talking about the same thing.

This issue is that instead of writing
`{% if phases.PHASENAME == 'PHASEVALUE' %}`
it would be possible to do this with same result, nothing more, nothing less 
`{% if phases.PHASENAME.PHASEVALUE %}`

(and I agree it might not be a good idea to do it after all)

**Comment by benabraham** [comment]
Reality check: 100 uses of `phases` in templates. 10 are combination of two phases, 1 is combination of three phases. 

While I still think, that it would make for a more _beautiful_  and _readable_ code (compare
`{% if phases.finaid == 'closed' or phases.finaid == 'awarded' %}d{% endif %}` with `{% if phases.finaid.closed or phases.finaid.awarded %}d{% endif %}`) it's not that bad and it's better to have _one way_ of doing this than two. Also while keeping this codebase _simpler_ and as our resources are limited let's get rid of one low severity issue and close it.

Zen of Python aphorisms referenced in this comment:
- Beautiful is better than ugly.
- Simple is better than complex.
- Readability counts.
- There should be one-- and preferably only one --obvious way to do it.
